### ISSUE TITLE
Error in building process:  python_bindings.cpp

### ISSUE THREAD

**Issue by edersonrmachado** [SpectreJan/libpmt#1]
Hi @SpectreJan thanks for this great project, I would like to use gnuradio pmt as standalone library, but installation, ( following recommended steps on ubuntu, after installing pybind11 and using python 3.6 ), results in this error in build step 10 of 11:

![Screenshot from 2020-11-23 02-16-08](https://user-images.githubusercontent.com/13380511/99931045-e7c49680-2d31-11eb-924d-fb7a2f718654.png)

Do you have an idea how could I fix it?

**Comment by SpectreJan** [comment]
Hi @edersonrmachado 

this could be an issue with the version of pybind11. What Ubuntu version are you using? There is a "closed" issue for this in the pybind11 repository but people seem to still experience problems on Ubuntu18.04: 
https://github.com/pybind/pybind11/issues/890

So maybe you could try building pybind11 from source or installing via pip/PyPI.

**Comment by edersonrmachado** [comment]
Cool! Thanks for the tip and quick response, in fact as seen in pybind/pybind11#890 , this problem is related to the pybind11 module and ubuntu 18.04. I managed to solve it by reinstalling pybind11 from source. I'm closing this topic since the problem is not related to this module.
